[technote]
id = "SQR-097"
series_id = "SQR"
canonical_url = "https://sqr-097.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-097"
github_default_branch = "main"
date_created = 2024-12-20T13:53:29Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Stelios"
name.family = "Voutsinas"
internal_id = "voutsinass"
orcid = "https://orcid.org/0009-0003-4290-2942"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
